GET http://localhost:3000/categories HTTP/1.1

###
POST http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "name": "rtv"
}

###
DELETE http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "id":"60baa830c556d5288caea098"
}

###
PUT http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "id":"60baa830c556d5288caea098",
    "name": "pralki"
}